### ISSUE TITLE
Technical Debt Tracker

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.mozilla.org#1320]
META bug to track all the technical debt issues that need to be fixed/dealt with before/while we start to work on l10n from this repo and the dependent projects (brackets, publish.wm.org, etc.)

See https://github.com/mozilla/thimble.webmaker.org/issues/1317 for details on priority

### Thimble
- [x] [#1226](https://github.com/mozilla/thimble.webmaker.org/issues/1226) - Use real links instead of js generated redirects
- [x] [#1200](https://github.com/mozilla/thimble.webmaker.org/issues/1200) - Date db entry issues
- [x] [#509](https://github.com/mozilla/thimble.webmaker.org/issues/509) - Migrate from old-Thimble
- [x] [#482](https://github.com/mozilla/thimble.webmaker.org/issues/482) - Bugzilla triage

---
### Brackets
- [x] [#510](https://github.com/humphd/brackets/issues/268) - Shutdown camera after taking a selfie

---
### Publish
- [x] [#202](https://github.com/mozilla/publish.webmaker.org/issues/202) - /healthcheck route
- [x] [#189](https://github.com/mozilla/publish.webmaker.org/issues/189) - Encoding for published files
- [x] [#188](https://github.com/mozilla/publish.webmaker.org/issues/188) - Migrate from old-Thimble
- [x] [#165](https://github.com/mozilla/publish.webmaker.org/issues/165) - Project dates should be generated server-side

---

cc @simonwex, @hannahkane, @flukeout, @Pomax, @humphd

**Comment by gideonthomas** [comment]
Moving out of Jan 29th milestone since all that's left is the migration of old-thimble projects which will be done after we tackle localization
