### ISSUE TITLE
Add pref toggle for enabling/disabling slowparse and UI suggestions

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#2580]
I think we need to give people a way to disable the slowparse UI, since it's a pretty big change, and if you don't want it, it will be annoying.  I think most people will want it, but let's just preempt the fact that not everyone will.

I looked at our current toggle preferences to see if we could just reuse one of them, but we don't really have anything like this.  We might want to add a general one for all the various kinds of inline help we offer (code suggestions, for example).

NOTE: if we do this, we'll need to make sure we add a shim to Thimble's `bramble` API for the change to the service worker code in Brackets for the new API.

**Comment by marcobeltempo** [comment]
@flukeout I was reading over #2575 and love the addition of the inline slowparse.
I am interested in implementing a toggle feature to go with it. 

@humphd  Were you thinking about having a main inline toggle + each individual toggle or just the main one?

Is there a way to test https://mozillathimblelivepreview.net/bramble/slowparse/dist/hosted.html
locally?

**Comment by humphd** [comment]
@marcobeltempo I've assigned this to you.  Can you do a few things?

1) Can you help test the slowparse stuff as @flukeout discusses in https://github.com/mozilla/thimble.mozilla.org/issues/2575#issue-280636327?  Try and see if you can break it, find bugs, etc.

2) Work on this pref.  Doing this will be a multi-part operation, some in Thimble and some in Brackets.  You should begin with the Brackets stuff.  Here's a rough outline:

* We need to add new properties to the Bramble API used by Thimble.  Probably we need `getHints()`, `enableHints()`, and `disableHints()`.  See https://github.com/mozilla/brackets#bramble-instance-getters and https://github.com/mozilla/brackets#bramble-instance-methods.  Start by adding the docs to the `README.md`
* The code for those APIs goes in https://github.com/mozilla/brackets/blob/master/src/bramble/client/main.js.  You can look at the other prefs in there to see what you have to do.  Just follow the pattern.  This code lives in Brackets, but runs in the the Thimble window, and passes messages across to the Brackets iframe.
* Next you need to write the receiving end of this code that lives in Brackets.  That will live here: https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/lib/RemoteCommandHandler.js.  Probably what you need to do in response to these enable/disable calls is flip a preference to true/false, and @flukeout's code needs to read the value of that pref to determine when to show/hide itself.  I can guide you when you get this far.
* Then you'll need to write code in Thimble that uses this.  That's a two part process, too.  First you need to shim the Bramble API here: https://github.com/mozilla/thimble.mozilla.org/blob/master/public/editor/scripts/bramble-shim.js to add the new API bits.
* Next you'll need to actually wire this up, so there is a toggle UI that calls the correct Bramble API to enable/disable things.  Again, you can follow examples from the other toggles we have now, which all work this way.

Ask me/Luke any questions you might have, and we'll help you.

**Comment by marcobeltempo** [comment]
@humphd Thank you for the detailed guidance. I will start tackling this and update my status on each step as I go

**Comment by marcobeltempo** [comment]
Just a quick status update @humphd 
I've pushed my most recent changes to an issue branch on my forked repo. 
You can see the commit here: [/marcobeltempo/brackets/commit/c8d2bd4](https://github.com/marcobeltempo/brackets/commit/c8d2bd42b6079a9809ed7a11aba2ec9e03daba5d)

### To-do
- [x] Add getAllowHints()  to bramble API
- [x] Add enableHints() to bramble API
- [x] Add disableHints() to bramble API
- [x] Add code to `src/bramble/client/main.js`
- [x] Update README
- [ ] Implement response to enable/disable commands in  `/src/extensions/default/bramble/lib/RemoteCommandHandler.j`
- [ ] Shim Bramble API in thimble `/public/editor/scripts/bramble-shim.js `
- [ ] Wire up UI to call Bramble API

**Comment by marcobeltempo** [comment]
@humphd I've added the code to shim Bramble as well as the UI toggle. I just need some guidance in connecting with @flukeout code

**Comment by humphd** [comment]
I need to sync up with @flukeout to see what we're doing with the slowparse feature--there's no PR for it yet.  Probably the easiest thing will be to do something via a preference on the Brackets side, which I can talk you through.  Let me hear from Luke first.

**Comment by gideonthomas** [comment]
@humphd the PR is here: https://github.com/mozilla/brackets/pull/876. I think I was supposed to review it but it fell off my radar. I can review it this week, but feel free to get to it before I do.
